# Mellow colorscheme for kitty
cursor #e3e2e5
foreground #c9c7cd
background #000000
selection_foreground     #e0def4
selection_background     #403d52
# Black
color0  #000000
color8  #60728A
# Red
color1  #BF616A
color9  #C5727A
# Green
color2  #A3BE8C
color10 #B1C89D
# Yellow
color3  #D08770
color11 #D79784
# Blue
color4  #81A1C1
color12 #88C0D0
# Magenta
color5  #B48EAD
color13 #BE9DB8
# Cyan
color6  #8FBCBB
color14 #9FC6C5
# White
color7  #ECEFF4
color15 #E5E9F0

active_tab_foreground   #cac9dd
active_tab_background   #353539
inactive_tab_foreground #57575f
inactive_tab_background #1b1b1d

active_border_color   #57575f
inactive_border_color #2a2a2d
inactive_text_alpha   1.0
