#!/bin/bash

# Log that script started
echo "$(date): env-sync.sh starting" >> ~/niri_env_sync.log 

# Log current environment
echo "QT_QPA_PLATFORMTHEME: $QT_QPA_PLATFORMTHEME" >> ~/niri_env_sync.log

# Sync to systemd
systemctl --user import-environment NIRI_SOCKET QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM QT_WAYLAND_DISABLE_WINDOWDECORATION QT_AUTO_SCREEN_SCALE_FACTOR XDG_SESSION_TYPE DISPLAY WAYLAND_DISPLAY GDK_BACKEND MOZ_ENABLE_WAYLAND OZONE_PLATFORM ELECTRON_OZONE_PLATFORM_HINT

# Sync to dbus
dbus-update-activation-environment --systemd NIRI_SOCKET QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM QT_WAYLAND_DISABLE_WINDOWDECORATION QT_AUTO_SCREEN_SCALE_FACTOR XDG_SESSION_TYPE DISPLAY WAYLAND_DISPLAY GDK_BACKEND MOZ_ENABLE_WAYLAND OZONE_PLATFORM ELECTRON_OZONE_PLATFORM_HINT

echo "$(date): env-sync.sh completed" >> ~/niri_env_sync.log
