# Add your additional Hyprland configurations here
#
#auto starting process
# exec-once = $HOME/eww/target/release/eww open bar
#gesture
#workspace_swipe = true

## swapping escape and caps lock


# This is an additional key binding
bind = SUPER, SPACE, exec, albert toggle
# binding for ghostty
bind = SUPER SHIFT, RETURN,exec, ghostty
# toggle waybar
# bind = SUPER SHIFT, B, exec, ~/./dotfiles/.config/waybar/toggle.sh
# bind = SUPER SHIFT, M, exec, ~/.config/hypr/scripts/music_cava.sh

#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Blur for waybar
layerrule = blur, gtk-layer-shell
layerrule = ignorealpha 0.45, gtk-layer-shell
layerrule = blur, notifications
layerrule = ignorealpha 0.5, notifications
layerrule = blur, swayosd
layerrule = ignorealpha 0.8, swayosd
#gesture

gestures {
workspace_swipe = 1
workspace_swipe_fingers=3
workspace_swipe_distance=300
workspace_swipe_min_speed_to_force=10
workspace_swipe_create_new = true
workspace_swipe_cancel_ratio = 0.2
workspace_swipe_forever = true
}

# default = 0.88
windowrule = opacity 0.98, class:^(zen)$
decoration {
   blur {
    enabled = true
    size = 8
    passes = 1
    new_optimizations = yes
    ignore_opacity=true
    }
}

windowrule = opacity 0.85, class:^(obsidian)$
decoration {
   blur {
    enabled = true
    size = 6
    passes = 5
    new_optimizations = yes
    ignore_opacity=true
    }
}

windowrule = opacity 0.96, class:^(azuredatastudio-url-handler)$
decoration {
   blur {
    enabled = true
    size = 6
    passes = 5
    new_optimizations = yes
    ignore_opacity=true
    }
}


# windowrule = opacity 1, class:^(code)
# decoration {
#    blur {
#     enabled = true
#     size = 5
#     passes = 5
#     new_optimizations = yes
#
#     }
# }

# zed customisation
#
windowrule = opacity 0.9 , class:^(dev.zed.Zed)
decoration {
   blur {
    enabled = true
    size = 1
    passes = 5
    new_optimizations = yes

    }
}

# Anytype

windowrule = opacity 0.85, class:^(anytype)
decoration {
   blur {
    enabled = true
    size = 1
    passes = 5
    new_optimizations = yes

    }
}

# windowrule = opacity 0.99, class:^(jetbrains-idea-ce)
# decoration {
#    blur {
#     enabled = true
#     size = 1
#     passes = 5
#     new_optimizations = yes
#
#     }
# }

input {
    kb_options = caps:swapescape
}
# title bar
#
# windowrule = workspace special, class:org.gnome.clocks


# Ulauncher
# windowrule = noblur, class:(ulauncher)

# GTK
# windowrule = blur,class:^(gtk).*$
windowrule = opacity 0.98, class:^(gtk).*$
decoration {
   blur {
    enabled = true
    size = 8
    passes = 1
    new_optimizations = yes
    ignore_opacity=true
    }
}

windowrule = opacity 0.8, class:^(albert).*$
decoration {
   blur {
    enabled = true
    size = 8
    passes = 1
    new_optimizations = yes
    ignore_opacity=true
    }
}

general {
    col.active_border = rgba(7941ccee) rgba(ff0000ff) rgba(00ff00ff) 45deg
    col.inactive_border = rgba(000000ff)
}

animation = borderangle, 1, 100, linear, loop
